[Monday 7:34 PM] Snehal Lipare
# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
 
image:
  name: salesforce/salesforcedx:7.75.1-slim
 
pipelines:
  default:
    - step:
        script:
          - echo "Commited changes to a branch that does not match the listed branches in bitbucket-pipelines.yml."
          - echo "You can skip running pipline by adding [skip ci] or [ci skip] (with []) to the git commit message."
          - sfdx --version
          - sfdx plugins --core
  branches:
    TEST ORG:
     - step:
         script:
           - sfdx --version
           - sfdx force:auth:jwt:grant -f server.key -i $SFDC_CONSUMER_KEY -
[Monday 7:36 PM] Snehal Lipare
# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
 
image:
  name: salesforce/salesforcedx:7.75.1-slim
 
pipelines:
  default:
    - step:
        script:
          - echo "Commited changes to a branch that does not match the listed branches in bitbucket-pipelines.yml."
          - echo "You can skip running pipline by adding [skip ci] or [ci skip] (with []) to the git commit message."
          - sfdx --version
          - sfdx plugins --core
  branches:
    TEST ORG:
     - step:
         script:
           - sfdx --version
           - sfdx force:auth:jwt:grant -f server.key -i $SFDC_CONSUMER_KEY -u $SFDC_USER -d -s -r $SFDC_URL
           - sfdx force:mdapi:deploy -d src -w 60 -l NoTestRun -u $SFDC_USER
