# Unique name for this workflow
name: Deploy integration branch to integration and staging/uat orgs

# Definition when the workflow should run
on:
    push:
      paths:
        - 'force-app/**'

# Jobs to be executed
jobs:
    deploy-branch-to-QA-org:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:

            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                
            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              uses: sfdx-actions/setup-sfdx@v1
              with:
                sfdx-version: 'latest'

            # Install java as it is required for the next step
            - name: 'Installing java'
              run: |
                sudo apt-get update
                sudo apt install default-jdk

            # Install SFDX scanner
            - name: 'Installing SFDX scanner'
              run: sfdx plugins:install @salesforce/sfdx-scanner

            - name: 'Scan code'
              run: |
                  sfdx scanner:run --format csv --target './**/*.cls' --category "Design,Best Practices,Performance,Security"
